fail_fast: true
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.1
    hooks:
      - id: golangci-lint
