name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: ./.github/workflows/release_generic.yml
    with:
      snapshot: false
